projetocc3642::Veiculo
Random projetocc3642.Veiculo.r
Função que garante a posição randomica dos objetos.
Random projetocc3642.Veiculo.c
Função random dos carros, para garantir a aleatoriedade dos movimentos dos carros.
Random projetocc3642.Veiculo.cam
Função random dos caminhões, para garantir a aleatoriedade dos movimentos dos mesmos.
Random projetocc3642.Veiculo.motoca
Função random das motos, para garantir a aleatoriedade dos movimentos das mesmas.
Random projetocc3642.Veiculo.bici
int projetocc3642.Veiculo.meio
Referenced by projetocc3642.Veiculo.moveBicicleta.
int projetocc3642.Veiculo.x
Variável que faz com que a bicicleta se mova a cada 2 iterações.
Referenced by projetocc3642.Bicicleta.Bicicleta, projetocc3642.Caminhao.Caminhao, projetocc3642.Carro.Carro, projetocc3642.Moto.Moto, projetocc3642.Veiculo.Veiculo, projetocc3642.Veiculo.setX, projetocc3642.Veiculo.getX, projetocc3642.Veiculo.MoveX, projetocc3642.Veiculo.verificaX.
int projetocc3642.Veiculo.y
Coordenada x do veículo.
Referenced by projetocc3642.Bicicleta.Bicicleta, projetocc3642.Caminhao.Caminhao, projetocc3642.Carro.Carro, projetocc3642.Moto.Moto, projetocc3642.Veiculo.Veiculo, projetocc3642.Veiculo.setY, projetocc3642.Veiculo.getY, projetocc3642.Veiculo.MoveY, projetocc3642.Veiculo.verificaY.
int projetocc3642.Veiculo.velocidade
Coordenada x do veículo.
Referenced by projetocc3642.Bicicleta.Bicicleta, projetocc3642.Caminhao.Caminhao, projetocc3642.Carro.Carro, projetocc3642.Moto.Moto, projetocc3642.Veiculo.Veiculo, projetocc3642.Veiculo.getVelocidade.
boolean projetocc3642.Veiculo.fabrica
Velocidade do veículo.
Referenced by projetocc3642.Bicicleta.Bicicleta, projetocc3642.Caminhao.Caminhao, projetocc3642.Carro.Carro, projetocc3642.Moto.Moto, projetocc3642.Veiculo.Veiculo, projetocc3642.Veiculo.isFabrica, projetocc3642.Veiculo.setFabrica.
String projetocc3642.Veiculo.cor
Informa se o veículo está ou não em uma fábrica.
Referenced by projetocc3642.Bicicleta.Bicicleta, projetocc3642.Caminhao.Caminhao, projetocc3642.Carro.Carro, projetocc3642.Moto.Moto, projetocc3642.Veiculo.Veiculo, projetocc3642.Veiculo.getCor.
projetocc3642.Veiculo.Veiculo()
Inicialização das variáveis.
References projetocc3642.Veiculo.x, projetocc3642.Veiculo.y, projetocc3642.Veiculo.velocidade, projetocc3642.Veiculo.fabrica, projetocc3642.Veiculo.cor.
projetocc3642.Veiculo.Veiculo(int x, int y, int velocidade, String cor, boolean fabrica)
Construtor da superclasse Veículo Cria os veículos com variáveis que são recebidas na chamada das funções de cada veículo específico.
x y velocidade cor fabrica
References projetocc3642.Veiculo.x, projetocc3642.Veiculo.y, projetocc3642.Veiculo.velocidade, projetocc3642.Veiculo.cor, projetocc3642.Veiculo.fabrica.
int projetocc3642.Veiculo.setX()
Seta um valor aleatório para o parâmetro x do veículo.
O valor gerado para x
References projetocc3642.Veiculo.x.
Referenced by projetocc3642.Mundo.geraVeiculos, projetocc3642.Mundo.geraVeiculo.
int projetocc3642.Veiculo.setY()
Seta um valor aleatório para o parâmetro y do veículo.
O valor gerado para y
References projetocc3642.Veiculo.y.
Referenced by projetocc3642.Mundo.geraVeiculos, projetocc3642.Mundo.geraVeiculo.
int projetocc3642.Veiculo.getX()
O valor de x do veículo
References projetocc3642.Veiculo.x.
Referenced by projetocc3642.Veiculo.moveCarro, projetocc3642.Veiculo.moveCaminhao, projetocc3642.Veiculo.moveMoto, projetocc3642.Veiculo.moveBicicleta.
int projetocc3642.Veiculo.getY()
O valor de y do veículo
References projetocc3642.Veiculo.y.
Referenced by projetocc3642.Veiculo.moveCarro, projetocc3642.Veiculo.moveCaminhao, projetocc3642.Veiculo.moveMoto, projetocc3642.Veiculo.moveBicicleta.
void projetocc3642.Veiculo.MoveX(int x)
Troca o valor de x de acordo com o que for passado pela função dos veiculos.
x
References projetocc3642.Veiculo.x.
Referenced by projetocc3642.Veiculo.moveCarro, projetocc3642.Veiculo.moveCaminhao, projetocc3642.Veiculo.moveMoto, projetocc3642.Veiculo.moveBicicleta.
void projetocc3642.Veiculo.MoveY(int y)
Troca o valor de x de acordo com o que for passado pela função dos veiculos.
y
References projetocc3642.Veiculo.y.
Referenced by projetocc3642.Veiculo.moveCarro, projetocc3642.Veiculo.moveCaminhao, projetocc3642.Veiculo.moveMoto, projetocc3642.Veiculo.moveBicicleta.
boolean projetocc3642.Veiculo.isFabrica()
Se a posição do veículo é igual a da fábrica
References projetocc3642.Veiculo.fabrica.
void projetocc3642.Veiculo.setFabrica(boolean fabrica)
Define se o veículo está ou não dentro da fábrica, pois se estiver, um novo será gerado.
fabrica
References projetocc3642.Veiculo.fabrica.
String projetocc3642.Veiculo.getCor()
A cor do veículo
References projetocc3642.Veiculo.cor.
int projetocc3642.Veiculo.getVelocidade()
A velocidade do veículo
References projetocc3642.Veiculo.velocidade.
void projetocc3642.Veiculo.moveCarro(Carro carro)
Função que movimenta o carro, recebendo um objeto da classe carro como parâmetro.
Como dito na função abaixo, a estrutura presente na função move carro é a mesma para as outras 3 carro
References projetocc3642.Veiculo.getX, projetocc3642.Veiculo.MoveX, projetocc3642.Veiculo.verificaX, projetocc3642.Veiculo.getY, projetocc3642.Veiculo.MoveY, projetocc3642.Veiculo.verificaY.
void projetocc3642.Veiculo.moveCaminhao(Caminhao caminhao)
Função que movimenta o caminhão, recebendo um objeto da classe caminhão como parâmetro.
caminhao
References projetocc3642.Veiculo.getX, projetocc3642.Veiculo.MoveX, projetocc3642.Veiculo.verificaX, projetocc3642.Veiculo.getY, projetocc3642.Veiculo.MoveY, projetocc3642.Veiculo.verificaY.
void projetocc3642.Veiculo.moveMoto(Moto moto)
Função que movimenta a motoca, recebendo um objeto da classe motoca como parâmetro.
moto
References projetocc3642.Veiculo.getX, projetocc3642.Veiculo.MoveX, projetocc3642.Veiculo.verificaX, projetocc3642.Veiculo.getY, projetocc3642.Veiculo.MoveY, projetocc3642.Veiculo.verificaY.
void projetocc3642.Veiculo.moveBicicleta(Bicicleta bicicleta)
bicicleta
References projetocc3642.Veiculo.meio, projetocc3642.Veiculo.getX, projetocc3642.Veiculo.MoveX, projetocc3642.Veiculo.verificaX, projetocc3642.Veiculo.getY, projetocc3642.Veiculo.MoveY, projetocc3642.Veiculo.verificaY.
int projetocc3642.Veiculo.verificaX(int x)
Função que verifica se o veículo chegou ao fim do mundo em x e reseta a coordenada.
x a coordenada resetada
References projetocc3642.Veiculo.x.
Referenced by projetocc3642.Veiculo.moveCarro, projetocc3642.Veiculo.moveCaminhao, projetocc3642.Veiculo.moveMoto, projetocc3642.Veiculo.moveBicicleta.
int projetocc3642.Veiculo.verificaY(int y)
Função que verifica se o veículo chegou ao fim do mundo em y e reseta a coordenada.
y a coordenada resetada
References projetocc3642.Veiculo.y.
Referenced by projetocc3642.Veiculo.moveCarro, projetocc3642.Veiculo.moveCaminhao, projetocc3642.Veiculo.moveMoto, projetocc3642.Veiculo.moveBicicleta.