projetocc3642::Mundo
Veiculo projetocc3642.Mundo.v
Instanciando a superclasse Veiculo.
ArrayList<Carro> projetocc3642.Mundo.c
Criação dos ArrayLists.
ArrayList<Caminhao> projetocc3642.Mundo.ca
ArrayList de Carros.
ArrayList<Bicicleta> projetocc3642.Mundo.b
ArrayList de Caminhões.
ArrayList<Moto> projetocc3642.Mundo.m
ArrayList de Bicicletas.
int projetocc3642.Mundo.mapa[][][][]
ArrayList de Motos.
Mapa do mundo
Referenced by projetocc3642.Mundo.desenhaMundo, projetocc3642.Mundo.zeraMapa, projetocc3642.Mundo.geraVeiculos, projetocc3642.Mundo.geraVeiculo.
void projetocc3642.Mundo.desenhaMundo()
Função que desenha o mundo.
References projetocc3642.Mundo.mapa.
Referenced by projetocc3642.Mundo.atualizaMundo, projetocc3642.ProjetoCC3642.main.
void projetocc3642.Mundo.zeraMapa()
Função que limpa o rastro dos veículos.
References projetocc3642.Mundo.mapa.
Referenced by projetocc3642.Mundo.atualizaMundo.
void projetocc3642.Mundo.geraVeiculos()
Função que gera os veículos randomicamente.
References projetocc3642.Veiculo.setX, projetocc3642.Veiculo.setY, projetocc3642.Mundo.mapa.
Referenced by projetocc3642.ProjetoCC3642.main.
void projetocc3642.Mundo.detectaColisao()
Função de detecção de colisão.
Referenced by projetocc3642.Mundo.atualizaMundo.
void projetocc3642.Mundo.geraVeiculo()
Função que gera um veículo novo assim que o mesmo passa por uma fábrica.
References projetocc3642.Mundo.mapa, projetocc3642.Veiculo.setX, projetocc3642.Veiculo.setY.
Referenced by projetocc3642.Mundo.atualizaMundo.
void projetocc3642.Mundo.atualizaMundo()
Função que "movimenta" os veículos.
References projetocc3642.Mundo.geraVeiculo, projetocc3642.Mundo.detectaColisao, projetocc3642.Mundo.zeraMapa, projetocc3642.Mundo.desenhaMundo.
Referenced by projetocc3642.ProjetoCC3642.main.